server {
    listen 80;
    server_name water.earthguardinnovation.org;
    root /var/www/water.earthguardinnovation.org;
    index index.html dashboard.html;

    location / {
        try_files $uri $uri/ /dashboard.html;
    }
}
